"""Mock incident report generation."""

import logging
from datetime import datetime, timezone

from app.schemas.investigation import InvestigationResult, RiskAssessment
from app.schemas.response import IncidentReport, ResponseRecommendation

logger = logging.getLogger(__name__)


class MockReportService:
    async def generate(
        self,
        investigation: InvestigationResult,
        risk: RiskAssessment,
        response: ResponseRecommendation,
    ) -> IncidentReport:
        timeline_summary = []
        if investigation.timeline:
            timeline_summary = [
                f"{e.timestamp.isoformat()} — {e.stage}: {e.description}"
                for e in investigation.timeline.entries
            ]

        recommended = [f"[P{a.priority}] {a.action_type}: {a.description}" for a in response.actions]

        markdown = f"""# Incident Report: {investigation.incident_id}

## Executive Summary
{investigation.summary}

## Threat Classification
- **Category:** {investigation.threat_classification.value}
- **Severity:** {investigation.severity.value}
- **Risk Score:** {risk.risk_score}/100 ({risk.risk_level.value})

## Evidence-Backed Analysis
{investigation.explanation}

## MITRE ATT&CK Techniques
{', '.join(investigation.mitre_techniques) or 'N/A'}

## Attack Timeline
{chr(10).join(f'- {t}' for t in timeline_summary)}

## Recommended Response
{chr(10).join(f'- {r}' for r in recommended)}

## Business Impact
{risk.business_impact}

---
*Generated by SIH26 Cybersecurity Assistant — Mock Report Module*
"""

        report = IncidentReport(
            incident_id=investigation.incident_id,
            title="Multi-Stage Intrusion: Brute Force to Sensitive Data Access",
            generated_at=datetime.now(timezone.utc),
            executive_summary=investigation.summary,
            threat_classification=investigation.threat_classification,
            severity=investigation.severity,
            risk_level=risk.risk_level,
            risk_score=risk.risk_score,
            evidence=investigation.evidence,
            explanation=investigation.explanation,
            recommended_actions=recommended,
            mitre_techniques=investigation.mitre_techniques,
            timeline_summary=timeline_summary,
            markdown_content=markdown,
        )

        logger.info("Mock report generated for %s", investigation.incident_id)
        return report
